[pytest]
markers =
    smoke: marks tests as smoke tests (select with '-m smoke')
    regression: marks tests as regression tests
    sanity: marks tests as sanity tests
    api: marks tests as api tests
    e2e: marks tests as end-to-end tests
addopts = --html=reports/report.html --self-contained-html
